import { redirect, notFound } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, MessageCircle } from 'lucide-react'
import { createClient } from '@/lib/supabase/server'
import TestimonialsManager from '@/components/testimonials/TestimonialsManager'
import type { ChatTestimonial } from '@/components/testimonials/WhatsAppScreenshot'

interface PageProps {
  params: Promise<{ id: string }>
}

export default async function ProductTestimonialsPage({ params }: PageProps) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: product } = await supabase
    .from('products')
    .select('id, title, description')
    .eq('id', id)
    .eq('seller_id', user.id)
    .maybeSingle()

  if (!product) notFound()

  const { data: testimonials } = await supabase
    .from('chat_testimonials')
    .select('*')
    .eq('product_id', id)
    .eq('seller_id', user.id)
    .order('sort_order', { ascending: true })
    .order('created_at', { ascending: true })

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
        {/* Breadcrumb */}
        <div className="flex items-center gap-3 mb-8">
          <Link
            href="/dashboard/products"
            className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-800 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Products
          </Link>
          <span className="text-gray-300">/</span>
          <Link
            href={`/dashboard/products/${id}/edit`}
            className="text-sm text-gray-500 hover:text-gray-800 truncate max-w-xs transition-colors"
          >
            {product.title}
          </Link>
          <span className="text-gray-300">/</span>
          <span className="text-sm font-semibold text-brand-black flex items-center gap-1.5">
            <MessageCircle className="w-4 h-4 text-[#25d366]" />
            Screenshot Testimonials
          </span>
        </div>

        <div className="mb-8">
          <h1 className="text-3xl font-black text-brand-black">Screenshot Testimonials</h1>
          <p className="text-gray-500 mt-1.5 text-sm max-w-2xl">
            Create realistic WhatsApp-style chat screenshots to display as verified reviews on your product page. Content is generated by AI and fully editable.
          </p>
        </div>

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6 lg:p-8">
          <TestimonialsManager
            productId={product.id}
            productTitle={product.title}
            productDescription={product.description ?? ''}
            initialTestimonials={(testimonials ?? []) as ChatTestimonial[]}
          />
        </div>
      </div>
    </div>
  )
}
